### PR TITLE
update oclif cli

### PR DESCRIPTION
**Pull request by vashian**

### CODE REVIEW

**Comment by mhemrg** [comment]
@userdehghani Please try this out in your local environment.

**Comment by userdehghani** [comment]
@mhemrg do we have need to keep `@oclif/command` in `bin/run`?

**Comment by vashian** [comment]
I was trying to get rid of the `@oclif/command` from `bin/run` 
After that when I tested it I got different output

**Comment by userdehghani** [comment]
@vashian Give me more details about what you changed, what you got and mention how can i help you?

also, i suggest to running these commands before making or updating PR on this repo:

```bash
npm run prepack
npm run postpack
```

**Comment by vashian** [comment]
@mhemrg I have to say `@oclif/core` removed `-h` as a short flag for `--help` and `-v` as a short flag for `--version`
Because they want to make it optional, From now on you can use `-h` or `-v` for other purposes.
However, based on this [article](https://github.com/oclif/core/blob/main/MIGRATION.md#restore--h--v-and-version) for restoring that functionality we need to add extra properties to our `package.json`

**Comment by vashian** [comment]
@userdehghani Thank you so much for your assistance 🌷
I got distracted and missed the ship

**Comment by mhemrg** [comment]
@vashian Yes, please restore the original functionality.

**Comment by mhemrg** [comment]
LGTM :)

**Pull request merged**
