### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by guoard**

### CODE REVIEW

**Comment by mhemrg** [comment]
Having a command like: `liara wp ls` is more appropriate.

**Comment by guoard** [comment]
> Having a command like: `liara wp ls` is more appropriate.

Unfortunately, this doesn't solve our problem either. Users are unable to select WordPress plus apps in the `shell` and `deploy` commands. It appears that we need to modify the API to address this issue.

**Comment by mhemrg** [comment]
Users shouldn't use `deploy` command on wordpress plus apps.

**Comment by mhemrg** [comment]
For `liara shell` access, we should keep using the `liara shell -a wp-app` command. We can show this command in the `overview` page of WordPress apps in our console.

**Pull request closed without merging**
